### ISSUE TITLE
Hydration Mismatch error

### ISSUE THREAD

**Issue by PeterDraex** [solidjs/solid#2132]
### Describe the bug

Getting an error:
> Error: Hydration Mismatch. Unable to find DOM nodes for hydration key: s00-0-0-0-0-0-0-0-0-1-3

### Your Example Website or App

https://stackblitz.com/edit/github-pqy8j7-jhayd9?file=src%2Fcomponents%2FPage.tsx

### Steps to Reproduce the Bug or Issue

1. Open console
2. See Hydration Mismatch Error

### Expected behavior

Blank page is displayed, with no errors in console.

### Platform

Windows, Chrome 123

**Comment by elite174** [comment]
This was solved here: https://discord.com/channels/722131463138705510/1229910798135066716/1230151418569298052

**Comment by PeterDraex** [comment]
> This was solved here: https://discord.com/channels/722131463138705510/1229910798135066716/1230151418569298052

Yeah, a workaround of `deferStream: true` was suggested on Discord. Another available workaround is using `<Show>` instead of `<Switch>`. 

The issue seems to be that as soon as Switch matches a case it renders and flushes the data. So in this case when `pending` case is matched it renders that and then yields.

**Comment by indeyets** [comment]
it works a bit different with solid-query 5.29:

1. seems to reach success-state
2. but still shows Hydration Mismatch in console

**Comment by indeyets** [comment]
attn @ardeora

**Comment by ryansolid** [comment]
It's pretty hard for me to debug Solid Query stuff. Like I need to put time aside to get into the code base. It might be easiest to report bugs against them and then they make reproductions with pure `createResource` so I can better see what is going on without tracing through that code.

**Comment by ardeora** [comment]
> It's pretty hard for me to debug Solid Query stuff. Like I need to put time aside to get into the code base. It might be easiest to report bugs against them and then they make reproductions with pure `createResource` so I can better see what is going on without tracing through that code.

Apologies @ryansolid Here is an example with just using `createResource`. 
https://stackblitz.com/edit/github-pqy8j7-n87wnf?file=src%2Fcomponents%2FPage.tsx

I think the Switch component eagerly evaluates and flushes the data when any case matches? In this case you would always see the `pending` string in the HTML after hydration

**Comment by ryansolid** [comment]
Sorry took me a while to look at this. But in the `createResource` scenario it is acting how I'd expect. The problem is that checking loading doesn't suspend.. the server doesn't wait. And in the client it is available and we get the mismatch unless the timing works out just right. You need to read the data to suspend.

If I remove the first condition or change the first switch condition to the following it works.
```js
<Match when={!data() && data.loading}>pending</Match>
```

The reason reading loading doesn't suspend is it is the mechanism we use to purposefully opt into tearing. But tearing during hydration won't work.

However making that fix in the Solid Query example I think still doesn't work. It doesn't error during hydration but it also doesn't show anything. So we will need to narrow this down further.

**Comment by ryansolid** [comment]
This is still open 2 years later so I'm considering this stale. I'm not investigating this further at this point with more narrowed Solid reproduction. And very soon we are on to 2.0. I suggest keeping up on the Solid Query side until we can get a Solid reproduction. Re-open or submit a new issue if we can get this nailed down to a Solid bug. But otherwise I'm going to assume the issue is downstream.
